### ISSUE TITLE
Page "General Statistics" 404 error

### ISSUE THREAD

**Issue by VincentTam** [davan690/davan690.github.io#13]
The title says it all.

**Comment by davan690** [comment]
Thanks heaps for the comment bro. This is a first for me but this issue is fixed. Had a mistake in ymal header of general stats post. Thanks  again

**Comment by VincentTam** [comment]
You meant to link to this post: https://github.com/davan690/davan690.github.io/blob/master/_posts/2019-04-26-General-statistics.md?  It's now linked to "Ecological Statistics".
